// <auto-generated />
using ASP.NET_WebAppFromScratch.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASP.NET_WebAppFromScratch.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200607195002_AlterEmployeesSeedData")]
    partial class AlterEmployeesSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ASP.NET_WebAppFromScratch.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = 1,
                            Email = "mawas__7@gmail.com",
                            Name = "Awais"
                        },
                        new
                        {
                            Id = 2,
                            Department = 1,
                            Email = "asim__7@gmail.com",
                            Name = "Asim"
                        },
                        new
                        {
                            Id = 3,
                            Department = 2,
                            Email = "mustensar__7@gmail.com",
                            Name = "Mustensar"
                        },
                        new
                        {
                            Id = 4,
                            Department = 1,
                            Email = "ayesha__7@gmail.com",
                            Name = "Ayesha"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
